# Persistent CPU1 build additions. CCS includes this file after its generated makefiles.

C_SRCS += \
./APP/ecat/ecat_gpio.c

C_DEPS += \
./APP/ecat/ecat_gpio.d

OBJS += \
./APP/ecat/ecat_gpio.obj

ORDERED_OBJS += \
"./APP/ecat/ecat_gpio.obj"

APP/ecat/ecat_gpio.obj: ../APP/ecat/ecat_gpio.c
	@echo 'C2000 Compiler - building file: "$<"'
	"E:/CCS20/CCS20.5.0/ccs/tools/compiler/ti-cgt-c2000_25.11.0.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --idiv_support=idiv0 --tmu_support=tmu0 --vcu_support=vcrc -Ooff --include_path="C:/Users/yangshilin/Desktop/Embedded Learning/DSP_PMSM_project/TEST/me/c28388_4.0/Dual_CPU/cpu1" --include_path="C:/Users/yangshilin/Desktop/Embedded Learning/DSP_PMSM_project/TEST/me/c28388_4.0/Dual_CPU/cpu1/CPU1_FLASH/syscfg" --include_path="C:/Users/yangshilin/Desktop/Embedded Learning/DSP_PMSM_project/TEST/me/c28388_4.0/Dual_CPU/cpu1/device" --include_path="C:/ti/c2000/C2000Ware_26_00_00_00/driverlib/f2838x/driverlib/" --include_path="E:/CCS20/CCS20.5.0/ccs/tools/compiler/ti-cgt-c2000_25.11.0.LTS/include" --define=_FLASH --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="APP/ecat/ecat_gpio.d_raw" --obj_directory="APP/ecat" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '
